config/routes.rb
TenThousandHours::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  resource :profile do 
    put :target
  end

  resources :users
  resources :records
  resources :targets
  resources :messages
  resources :followships

  get "home/index"
  get "home/record"
  get "home/period"
  get "home/select_user"

  root to: 'home#index'

end

app/models/target.rb
class Target < ActiveRecord::Base
  validates_uniqueness_of :name
  attr_accessible :name, :description
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @targets }
    end
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
    @target = Target.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @target }
    end
  end

  # GET /targets/new
  # GET /targets/new.json
  def new
    @target = Target.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @target }
    end
  end

  # GET /targets/1/edit
  def edit
    @target = Target.find(params[:id])
  end

  # POST /targets
  # POST /targets.json
  def create
    @target = Target.new(params[:target])

    respond_to do |format|
      if @target.save
        format.html { redirect_to @target, notice: 'Target was successfully created.' }
        format.json { render json: @target, status: :created, location: @target }
      else
        format.html { render action: "new" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /targets/1
  # PUT /targets/1.json
  def update
    @target = Target.find(params[:id])

    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target = Target.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.haml
= simple_form_for(@target) do |f|
  = f.error_notification

  .form-inputs
    = f.input :description

  .form-actions
    = f.button :submit

app/views/targets/edit.html.haml
%h1 Editing target

= render 'form'

= link_to 'Show', @target
\|
= link_to 'Back', targets_path

app/views/targets/index.html.haml
%h1 Listing targets

%table
  %tr
    %th Description
    %th
    %th
    %th

  - @targets.each do |target|
    %tr
      %td= target.description
      %td= link_to 'Show', target
      %td= link_to 'Edit', edit_target_path(target)
      %td= link_to 'Destroy', target, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Target', new_target_path

app/views/targets/new.html.haml
%h1 New target

= render 'form'

= link_to 'Back', targets_path

app/views/targets/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @target.description

= link_to 'Edit', edit_target_path(@target)
\|
= link_to 'Back', targets_path