config/routes.rb
TenThousandHours::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  resource :profile do 
    put :target
  end

  resources :users
  resources :records
  resources :targets
  resources :messages
  resources :followships

  get "home/index"
  get "home/record"
  get "home/period"
  get "home/select_user"

  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def record
    render partial: "home/record", content_type: "text/html"
  end

  def period
    from = params[:from].to_i
    to = params[:to].to_i
    return render inline: "from is bigger then to" if from > to
    return render inline: "interval too large" if to - from > 1000
    render partial: "time_period", locals: {from: from, to: to}, content_type: "text/html"
  end

  def select_user
    @user = User.find params[:user_id]
    render partial: "user_control", content_type: "text/html"
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
  def user_pos user
    left = (user.email.hash % 8)*100 + 190
    left = 90 if user == current_user
    top = user.profile.total_spend * 10
    "top: #{top}px; left: #{left}px"
  end

  def user_traces user
    user.records.order('id desc').limit(1).reverse
  end

  def traces_height traces
    count = traces.map(&:spend).inject{|sum,x| sum + x }
    height = (count || 0) * 10
  end

  def user_statistic_data user
    data = {}

    {week: 7, month: 30, year: 365}.each do |k, v|
      data[k] = [0] * v
      user.records
        .where('created_at > ?', Time.now - v.days)
        .order('created_at desc')
        .each do |r|
        day = (r.created_at - (Time.now - v.days)) / (3600*24)
        data[k][day] = r.spend
      end
    end

    data
  end
end

app/views/home/_record.haml
- if not user_signed_in?
  .span2.offset5
    %a.btn.btn-success.join{href: new_user_registration_path}
      = "加入！"

- elsif not current_user.profile.target
  .span3.offset4
    = "选择您的目标："
    %select.span2
      - Target.order('id desc').each do |t|
        %option= t.name
  .span2
    = button_to "就是它了！", target_profile_path, class: "btn btn-success", method: :put

- elsif not current_user.record_today?
  .span2.offset5
    %a.btn.btn-success.record#btn_record_today
      = "本日记录"
  = render partial: "records/dlg", locals: {record: Record.new}

- else
  - record = current_user.last_record
  .span4.offset4.center
    %p
      您今天做了#{record.spend}小时， 请明天再接再厉！
  .span4.offset4.center
    %a.btn.btn-success.record#btn_record_today
      = "更新本日记录"
  = render partial: "records/dlg", locals: {record: record}

app/views/home/_time_period.haml
.time_period
  - users = Timeline.users(from, to).limit(12)
  .users
    - users.each do |user|
      .user.user_head{:"data-user_id" => user.id, style: user_pos(user), "data-user_name" => user.name, "data-user_summary" => (user.last_record.summary rescue "")}
        .img= user_image user
        - if signed_in? and user == current_user
          .i_am_here= t(".i_am_here")

  .traces
    - users.each do |user|
      .user.user_trace{:"data-user_id" => user.id, style: user_pos(user)}
        - traces = user_traces user
        - height = traces_height traces
        .traces{style: "height: #{height}px; top: -#{height}px"}
          - traces.each_with_index do |r, i|
            .trace{style: "height: #{r.spend * 10}px", class: "trace-#{i}"}

  .milestones
    - Timeline.milestones(from, to).each do |m|
      .milestone{style: "top: #{m * 10}px"}
        .hour= "#{m} hours"

app/views/home/_timeline.haml
#timeline
  %a.btn.timeline_up= t(".up")
  %a.btn.timeline_down= t(".down")

  #middleline

  #metric
    = render partial: "time_period", locals: user_signed_in? ? current_user.display_scale : {from: 0, to: 20}
#timeline_ctr.Clearfix
  %span.start 0 hours
  %input.timeline_slider{type:"range",min:0,max:10000,step:10}
  %span.end  10k  hours
  
.clearfix
#selected_user_outter

app/views/home/_title.haml
.home_title
  %h1 10000 Hours
  .row
    .span4.offset4
      %p.desc= t(".desc")

  .row.record_control= render partial: "home/record"

app/views/home/_user_control.haml
- selected_user = @user
#selected_user.row{"data-user_id" => selected_user.id}
  .title.span4.offset4
    = user_image selected_user
    = selected_user.last_record.summary rescue ""
  .span4.offset4
    .btn-toolbar

      .btn-group
        %a.btn.btn-primary.msg_btn{"data-kind" => "up"}
          %i.icon-thumbs-up
          = "鼓励一下"
        %a.btn.btn-primary.msg_btn{"data-kind" => "down"}
          %i.icon-exclamation-sign
          = "督促一下"
        %a.btn.btn-primary.follow_btn
          %i.icon-eye-open
          = "关注"
        %a.btn.btn-info{href: user_path(selected_user), target: "_blank"}
          %i.icon-user
          = "用户信息"

  .msg_form.span4.offset4

:coffeescript
  init_timeline_user_control()

app/views/home/index.html.haml
= render partial: "title"
= render partial: "timeline"
= render partial: "activities/list", locals: {activities: Activity.order('id desc').first(10)}

- content_for :script do
  - current_spend = user_signed_in? ? current_user.profile.total_spend : 0
  :coffeescript
    $ init_timeline current: #{current_spend}
    $ init_record_control