config/routes.rb
TenThousandHours::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  resource :profile do 
    put :target
  end

  resources :users
  resources :records
  resources :targets
  resources :messages
  resources :followships

  get "home/index"
  get "home/record"
  get "home/period"
  get "home/select_user"

  root to: 'home#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :user
  belongs_to :target
  attr_accessible :target, :spend, :summary

  def spend
    self[:spend] || 0
  end

  def summary
    self[:summary] || ""
  end

  after_save {self.user.profile.update_total_spend}

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = current_user.records.new( params[:record].slice(:summary, :spend) )
    @record.target = current_user.profile.target

    respond_to do |format|
      if @record.save
        return redirect_to "/"
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        return redirect_to "/"
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_dlg.haml
.modal.hide.fade#record_dlg
  = simple_form_for(record, remote: true) do |f|
    = f.error_notification
  
    .form-inputs
      = f.input :spend
      = f.input :summary, input_html: {rows: 5}
  
    .form-actions
      = f.button :submit

app/views/records/_form.html.haml
= simple_form_for(@record) do |f|
  = f.error_notification

  .form-inputs
    = f.input :spend
    = f.input :summary

  .form-actions
    = f.button :submit

app/views/records/edit.html.haml
%h1 Editing record

= render 'form'

= link_to 'Show', @record
\|
= link_to 'Back', records_path

app/views/records/index.html.haml
%h1 Listing records

%table
  %tr
    %th User
    %th Target
    %th Spend
    %th Summary
    %th
    %th
    %th

  - @records.each do |record|
    %tr
      %td= record.user
      %td= record.target
      %td= record.spend
      %td= record.summary
      %td= link_to 'Show', record
      %td= link_to 'Edit', edit_record_path(record)
      %td= link_to 'Destroy', record, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Record', new_record_path

app/views/records/new.html.haml
%h1 New record

= render 'form'

= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice

%p
  %b User:
  = @record.user
%p
  %b Target:
  = @record.target
%p
  %b Spend:
  = @record.spend
%p
  %b Summary:
  = @record.summary

= link_to 'Edit', edit_record_path(@record)
\|
= link_to 'Back', records_path