config/routes.rb
TenThousandHours::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  resource :profile do 
    put :target
  end

  resources :users
  resources :records
  resources :targets
  resources :messages
  resources :followships

  get "home/index"
  get "home/record"
  get "home/period"
  get "home/select_user"

  root to: 'home#index'

end

app/views/layouts/_messages.haml
%li.dropdown
  - messages = current_user.unread_messages
  %a{href: messages_path}
    %span.message_count{class: messages.length > 0 ? "present" : ""}= messages.length
    条新消息

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "TenThousandHours"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link{href: image_path("favicon.ico"), rel: "shortcut icon"}
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") TenThousandHours

          %ul.nav.pull-right
            - if user_signed_in?
              = render partial: "layouts/messages"
              %li= link_to current_user.name, profile_path
              %li= link_to t('.followings'), followships_path
              %li= link_to t('.logout'), destroy_user_session_path, method: :delete
            - else
              %li= link_to t('.login'), new_user_session_path
              %li= link_to t('.register'), new_user_registration_path

    .container

      .content
        .row
          .span12#notice= notice

        .row
          .span12
            = yield
    
      %footer
        -# %p &copy; 2012

    = javascript_include_tag "application"
    = yield(:script)